import type { Classification, ClassificationStatus } from '../../types/classification';
import type { DashboardActivity, DashboardFilters } from '../../types/dashboard';
import type { UploadReviewItem } from '../../types/upload';
export const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
export function filterClassifications(rows: Classification[], filters: DashboardFilters) { return rows.filter((r)=> (filters.year === 'Todos' || String(r.ejercicio) === filters.year) && (filters.market === 'Todos' || r.mercado === filters.market)); }
export function buildMetrics(rows: Classification[], uploads: UploadReviewItem[]) { return { total: rows.length, vigente: rows.filter(r=>r.estado==='Vigente').length, pendiente: rows.filter(r=>r.estado==='Pendiente').length, observada: rows.filter(r=>r.estado==='Observada').length, montoTotal: rows.reduce((s,r)=>s+r.monto,0), cargas: uploads.length, filasConError: uploads.reduce((s,u)=>s+u.invalidRows,0) }; }
export function statusItems(rows: Classification[]) { const statuses: ClassificationStatus[] = ['Vigente','Pendiente','Observada','Rechazada']; return statuses.map((label)=>({ label, value: rows.filter((r)=>r.estado===label).length })); }
export function marketAmounts(rows: Classification[]) { return ['Acciones','Renta Fija','Fondos'].map((label)=>({ label, value: rows.filter((r)=>r.mercado===label).reduce((s,r)=>s+r.monto,0), formattedValue: money.format(rows.filter((r)=>r.mercado===label).reduce((s,r)=>s+r.monto,0)) })); }
export function recentActivity(rows: Classification[], uploads: UploadReviewItem[], extra: DashboardActivity[]) { const cls = rows.slice(-4).map((r)=>({ id:`act-${r.id}`, date:r.fechaPago.split('-').reverse().join('-'), type:'Calificación', description:`${r.instrumento} · ${r.descripcion}`, owner:r.origen, status:r.estado, actionLabel:'Ver Calificaciones', actionPath:'/calificaciones' })); const ups = uploads.map((u)=>({ id:`act-${u.id}`, date:u.date, type:u.type==='x-factor'?'Carga X Factor':'Carga X Monto', description:u.fileName, owner:u.owner, status:u.status, actionLabel:u.type==='x-factor'?'Ver Carga X Factor':'Ver Carga X Monto', actionPath:u.type==='x-factor'?'/cargas/x-factor':'/cargas/x-monto' })); return [...cls, ...ups, ...extra].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8); }
