namespace NuamExchange.Application.TaxReports;

public sealed record TaxClassificationReportQuery(string? Market, string? InstrumentCode, int? TaxPeriod, string? Status, string? ClassificationType, string? Currency, int Page = TaxClassificationReportDefaults.DefaultPage, int PageSize = TaxClassificationReportDefaults.DefaultPageSize, string? SortBy = TaxClassificationReportDefaults.DefaultSortBy, string SortDirection = TaxClassificationReportDefaults.DefaultSortDirection);
public static class TaxClassificationReportDefaults { public const int DefaultPage = 1; public const int DefaultPageSize = 20; public const int MaxPageSize = 100; public const int MaxExportRows = 10000; public const string DefaultSortBy = "taxPeriod"; public const string DefaultSortDirection = "desc"; }
public sealed record ValidatedTaxClassificationReportQuery(string? Market, string? InstrumentCode, int? TaxPeriod, string? Status, string? ClassificationType, string? Currency, int Page, int PageSize, string SortBy, string SortDirection);
public sealed record TaxClassificationReportValidationResult(bool Succeeded, ValidatedTaxClassificationReportQuery? Query, string? Message) { public static TaxClassificationReportValidationResult Success(ValidatedTaxClassificationReportQuery query) => new(true, query, null); public static TaxClassificationReportValidationResult Failure(string message) => new(false, null, message); }
public interface ITaxReportQueryValidator { TaxClassificationReportValidationResult Validate(TaxClassificationReportQuery query); }
public interface ITaxReportQueryService { Task<TaxClassificationReportDto> GetTaxClassificationsAsync(ValidatedTaxClassificationReportQuery query, CancellationToken cancellationToken = default); Task<TaxClassificationCsvExportDto> ExportTaxClassificationsAsync(ValidatedTaxClassificationReportQuery query, CancellationToken cancellationToken = default); }
public sealed record TaxClassificationReportDto(DateTime GeneratedAt, TaxClassificationReportAppliedFiltersDto AppliedFilters, TaxClassificationReportSummaryDto Summary, IReadOnlyCollection<TaxClassificationReportItemDto> Items, int Page, int PageSize, int TotalCount, int TotalPages);
public sealed record TaxClassificationReportAppliedFiltersDto(string? Market, string? InstrumentCode, int? TaxPeriod, string? Status, string? ClassificationType, string? Currency, string SortBy, string SortDirection);
public sealed record TaxClassificationReportSummaryDto(int TotalClassifications, IReadOnlyCollection<TaxClassificationReportCountDto> CountByStatus, IReadOnlyCollection<TaxClassificationReportCountDto> CountByClassificationType, int CountWithAppliedFactor, int CountWithReferenceAmount, IReadOnlyCollection<TaxClassificationReportCurrencyTotalDto> ReferenceAmountTotalsByCurrency);
public sealed record TaxClassificationReportCountDto(string Value, int Count);
public sealed record TaxClassificationReportCurrencyTotalDto(string Currency, int Count, decimal TotalReferenceAmount);
public sealed record TaxClassificationReportItemDto(int Id, string Market, string? InstrumentCode, string? InstrumentName, string ClassificationType, int TaxPeriod, string Status, decimal? AppliedFactor, decimal? ReferenceAmount, string Currency, DateOnly ValidFrom, DateOnly? ValidTo, DateTime UpdatedAt);
public sealed record TaxClassificationCsvExportDto(byte[] Content, string FileName, string ContentType);
