// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuamExchange.Infrastructure.Persistence;

#nullable disable

namespace NuamExchange.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NuamExchangeDbContext))]
    [Migration("20260622200947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NuamExchange.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("cargo");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("ultimo_acceso_en");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auditoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("ActionAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_accion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("AffectedEntity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("entidad_afectada");

                    b.Property<int?>("AffectedRecordId")
                        .HasColumnType("int")
                        .HasColumnName("registro_afectado_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(900)
                        .HasColumnType("nvarchar(900)")
                        .HasColumnName("detalle");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_nuevo");

                    b.Property<string>("OriginIp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_anterior");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AffectedEntity", "ActionAt")
                        .IsDescending(false, true);

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BackupRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("respaldo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackupAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_respaldo")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("BackupPath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("ruta_respaldo");

                    b.Property<string>("BackupStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("PROGRAMADO")
                        .HasColumnName("estado_respaldo");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_respaldo");

                    b.Property<string>("Observation")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("observacion");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Respaldo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Respaldo_EstadoRespaldo", "[estado_respaldo] IN ('PROGRAMADO','EJECUTADO','FALLIDO','RESTAURADO')");

                            t.HasCheckConstraint("CK_Respaldo_TipoRespaldo", "[tipo_respaldo] IN ('BASE_DATOS','ARCHIVOS','COMPLETO')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BulkUploadDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_carga_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedField")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("campo_afectado");

                    b.Property<decimal?>("AmountValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("valor_monto");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal?>("FactorValue")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("valor_factor");

                    b.Property<string>("Observation")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("observacion");

                    b.Property<string>("OriginalTextValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("valor_texto_original");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("numero_fila");

                    b.Property<string>("RowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado_fila");

                    b.Property<int?>("TaxClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("calificacion_id");

                    b.Property<int>("UploadFileId")
                        .HasColumnType("int")
                        .HasColumnName("archivo_carga_id");

                    b.HasKey("Id");

                    b.HasIndex("TaxClassificationId");

                    b.HasIndex("UploadFileId", "RowNumber");

                    b.ToTable("DetalleCargaMasiva", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleCargaMasiva_EstadoFila", "[estado_fila] IN ('PENDIENTE','VALIDA','CON_ERROR','APLICADA','IGNORADA')");

                            t.HasCheckConstraint("CK_DetalleCargaMasiva_NumeroFila", "[numero_fila] > 0");

                            t.HasCheckConstraint("CK_DetalleCargaMasiva_ValorFactor", "[valor_factor] IS NULL OR [valor_factor] >= 0");

                            t.HasCheckConstraint("CK_DetalleCargaMasiva_ValorMonto", "[valor_monto] IS NULL OR [valor_monto] >= 0");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BulkUploadError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("error_carga_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("columna");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ErrorDescription")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("descripcion_error");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int")
                        .HasColumnName("numero_fila");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("ERROR")
                        .HasColumnName("severidad");

                    b.Property<int>("UploadFileId")
                        .HasColumnType("int")
                        .HasColumnName("archivo_carga_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadFileId", "RowNumber");

                    b.ToTable("ErrorCargaMasiva", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErrorCargaMasiva_NumeroFila", "[numero_fila] IS NULL OR [numero_fila] > 0");

                            t.HasCheckConstraint("CK_ErrorCargaMasiva_Severidad", "[severidad] IN ('ADVERTENCIA','ERROR','CRITICO')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.ClassificationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("historial_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("tipo_cambio");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ModifiedField")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("campo_modificado");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_nuevo");

                    b.Property<string>("Observation")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("observacion");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_anterior");

                    b.Property<int>("TaxClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("calificacion_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TaxClassificationId", "ChangedAt")
                        .IsDescending(false, true);

                    b.ToTable("HistorialCalificacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_HistorialCalificacion_TipoCambio", "[tipo_cambio] IN ('CREACION','MODIFICACION','ANULACION','REEMPLAZO','OBSERVACION','APROBACION')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("codigo");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_permiso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("calificacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AppliedFactor")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("factor_aplicado");

                    b.Property<string>("ClassificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_calificacion");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_creador_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("CLP")
                        .HasColumnName("moneda");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("InstrumentCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("codigo_instrumento");

                    b.Property<string>("InstrumentName")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)")
                        .HasColumnName("nombre_instrumento");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("mercado");

                    b.Property<decimal?>("ReferenceAmount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("monto_referencia");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("VIGENTE")
                        .HasColumnName("estado_calificacion");

                    b.Property<int>("TaxPeriod")
                        .HasColumnType("int")
                        .HasColumnName("periodo_tributario");

                    b.Property<decimal?>("UpdatePercentage")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("porcentaje_actualizacion");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("Market", "ClassificationType");

                    b.HasIndex("TaxPeriod", "Status");

                    b.HasIndex("ValidFrom", "ValidTo");

                    b.ToTable("CalificacionTributaria", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalificacionTributaria_Estado", "[estado_calificacion] IN ('BORRADOR','VIGENTE','OBSERVADA','REEMPLAZADA','ANULADA')");

                            t.HasCheckConstraint("CK_CalificacionTributaria_FactorAplicado", "[factor_aplicado] IS NULL OR [factor_aplicado] >= 0");

                            t.HasCheckConstraint("CK_CalificacionTributaria_MontoReferencia", "[monto_referencia] IS NULL OR [monto_referencia] >= 0");

                            t.HasCheckConstraint("CK_CalificacionTributaria_PeriodoTributario", "[periodo_tributario] BETWEEN 2000 AND 2100");

                            t.HasCheckConstraint("CK_CalificacionTributaria_PorcentajeActualizacion", "[porcentaje_actualizacion] IS NULL OR [porcentaje_actualizacion] >= 0");

                            t.HasCheckConstraint("CK_CalificacionTributaria_Vigencia", "[vigente_hasta] IS NULL OR [vigente_desde] <= [vigente_hasta]");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reporte_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedFilters")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filtros_aplicados");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("formato");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("generado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ReportPath")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("ruta_reporte");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_reporte");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GeneratedAt")
                        .IsDescending(false, true);

                    b.ToTable("ReporteTributario", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReporteTributario_Formato", "[formato] IN ('PDF','XLSX','CSV')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("validacion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observation")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("observacion");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("resultado");

                    b.Property<int?>("TaxClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("calificacion_id");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("int")
                        .HasColumnName("archivo_carga_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("ValidatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_validacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TaxClassificationId", "ValidatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UploadFileId", "ValidatedAt")
                        .IsDescending(false, true);

                    b.ToTable("ValidacionTributaria", null, t =>
                        {
                            t.HasCheckConstraint("CK_ValidacionTributaria_Referencia", "[calificacion_id] IS NOT NULL OR [archivo_carga_id] IS NOT NULL");

                            t.HasCheckConstraint("CK_ValidacionTributaria_Resultado", "[resultado] IN ('VALIDADO','OBSERVADO','RECHAZADO','APROBADO')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("archivo_carga_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("registros_con_error");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("extension");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("hash_archivo");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("ruta_archivo");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<string>("Observation")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("observacion");

                    b.Property<int>("TotalRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_registros");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("RECIBIDO")
                        .HasColumnName("estado_carga");

                    b.Property<int>("UploadTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("plantilla_id");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("tipo_carga");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("fecha_carga")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("ValidRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("registros_validos");

                    b.HasKey("Id");

                    b.HasIndex("UploadTemplateId");

                    b.HasIndex("UploadType", "UploadStatus");

                    b.HasIndex("UserId", "UploadedAt")
                        .IsDescending(false, true);

                    b.ToTable("ArchivoCarga", null, t =>
                        {
                            t.HasCheckConstraint("CK_ArchivoCarga_Contadores", "[total_registros] >= 0 AND [registros_validos] >= 0 AND [registros_con_error] >= 0");

                            t.HasCheckConstraint("CK_ArchivoCarga_EstadoCarga", "[estado_carga] IN ('RECIBIDO','EN_VALIDACION','PROCESADO','PROCESADO_CON_ERRORES','OBSERVADO','RECHAZADO')");

                            t.HasCheckConstraint("CK_ArchivoCarga_Extension", "[extension] IN ('CSV','XLSX')");

                            t.HasCheckConstraint("CK_ArchivoCarga_Tamanio", "[tamanio_bytes] IS NULL OR [tamanio_bytes] > 0");

                            t.HasCheckConstraint("CK_ArchivoCarga_TipoCarga", "[tipo_carga] IN ('X_FACTOR','X_MONTO')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.UploadTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plantilla_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedFormat")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("formato_permitido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("RequiredColumns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("columnas_requeridas");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_plantilla");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("version_plantilla");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("tipo_carga");

                    b.HasKey("Id");

                    b.HasIndex("UploadType", "IsActive");

                    b.HasIndex("UploadType", "TemplateVersion")
                        .IsUnique();

                    b.ToTable("PlantillaCarga", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlantillaCarga_FormatoPermitido", "[formato_permitido] IN ('CSV','XLSX','CSV/XLSX')");

                            t.HasCheckConstraint("CK_PlantillaCarga_TipoCarga", "[tipo_carga] IN ('X_FACTOR','X_MONTO')");
                        });
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BackupRecord", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("BackupRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BulkUploadDetail", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.TaxClassification", "TaxClassification")
                        .WithMany("BulkUploadDetails")
                        .HasForeignKey("TaxClassificationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NuamExchange.Domain.Entities.UploadFile", "UploadFile")
                        .WithMany("Details")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaxClassification");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.BulkUploadError", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.UploadFile", "UploadFile")
                        .WithMany("Errors")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.ClassificationHistory", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.TaxClassification", "TaxClassification")
                        .WithMany("History")
                        .HasForeignKey("TaxClassificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("ClassificationHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaxClassification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NuamExchange.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxClassification", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "CreatorUser")
                        .WithMany("CreatedTaxClassifications")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxReport", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("TaxReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxValidation", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.TaxClassification", "TaxClassification")
                        .WithMany("TaxValidations")
                        .HasForeignKey("TaxClassificationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NuamExchange.Domain.Entities.UploadFile", "UploadFile")
                        .WithMany("TaxValidations")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("TaxValidations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaxClassification");

                    b.Navigation("UploadFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.UploadFile", b =>
                {
                    b.HasOne("NuamExchange.Domain.Entities.UploadTemplate", "UploadTemplate")
                        .WithMany("UploadFiles")
                        .HasForeignKey("UploadTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NuamExchange.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UploadFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UploadTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BackupRecords");

                    b.Navigation("ClassificationHistories");

                    b.Navigation("CreatedTaxClassifications");

                    b.Navigation("TaxReports");

                    b.Navigation("TaxValidations");

                    b.Navigation("UploadFiles");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.TaxClassification", b =>
                {
                    b.Navigation("BulkUploadDetails");

                    b.Navigation("History");

                    b.Navigation("TaxValidations");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.UploadFile", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Errors");

                    b.Navigation("TaxValidations");
                });

            modelBuilder.Entity("NuamExchange.Domain.Entities.UploadTemplate", b =>
                {
                    b.Navigation("UploadFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
