import { Button } from '../../components/Button';
import { StatusBadge } from '../../components/StatusBadge';
import type { AdministrationUser, UserAccountStatus, UserSortKey, UserSortState } from '../../types/administration';
import { formatDate } from './administrationUtils';

interface Props { users: AdministrationUser[]; sort: UserSortState; activeUserId: string; onSort: (key: UserSortKey) => void; onEdit: (user: AdministrationUser) => void; onStatus: (user: AdministrationUser, estado: UserAccountStatus) => void; onReset: (user: AdministrationUser) => void; }
const columns: { key: UserSortKey; label: string }[] = [{ key: 'nombre', label: 'Nombre' }, { key: 'email', label: 'Correo' }, { key: 'rol', label: 'Rol' }, { key: 'estado', label: 'Estado' }, { key: 'fechaCreacion', label: 'Fecha de creación' }, { key: 'ultimoAcceso', label: 'Último acceso' }];
export function UsersTable({ users, sort, activeUserId, onSort, onEdit, onStatus, onReset }: Props) {
  const ariaSort = (key: UserSortKey) => sort.key !== key ? 'none' : sort.direction === 'asc' ? 'ascending' : 'descending';
  return <div className="table-scroll"><table className="data-table admin-table"><caption>Usuarios administrativos simulados</caption><thead><tr>{columns.map((column) => <th key={column.key} aria-sort={ariaSort(column.key)}><button className="sortable-heading" onClick={() => onSort(column.key)}>{column.label}<span>{sort.key === column.key ? (sort.direction === 'asc' ? 'Ascendente' : 'Descendente') : 'Ordenar'}</span></button></th>)}<th>Creado por</th><th>Acciones</th></tr></thead><tbody>{users.map((user) => { const self = user.id === activeUserId; return <tr key={user.id}><td><strong>{user.nombre}</strong><br /><small>{user.id}</small></td><td>{user.email}</td><td>{user.rol}</td><td><StatusBadge status={user.estado} /></td><td>{formatDate(user.fechaCreacion)}</td><td>{formatDate(user.ultimoAcceso)}</td><td>{user.creadoPor}</td><td><div className="row-actions"><Button onClick={() => onEdit(user)}>Editar</Button>{user.estado !== 'Activo' && <Button disabled={self} onClick={() => onStatus(user, 'Activo')}>Activar</Button>}{user.estado === 'Activo' && <Button disabled={self} onClick={() => onStatus(user, 'Inactivo')}>Desactivar</Button>}{user.estado !== 'Bloqueado' && <Button disabled={self} onClick={() => onStatus(user, 'Bloqueado')}>Bloquear</Button>}{user.estado === 'Bloqueado' && <Button disabled={self} onClick={() => onStatus(user, 'Activo')}>Desbloquear</Button>}<Button onClick={() => onReset(user)}>Restablecer acceso</Button>{self && <small>No se permite cambiar tu estado activo.</small>}</div></td></tr>; })}</tbody></table></div>;
}
