import { useEffect, useRef, useState } from 'react';
import { Button } from '../../components/Button';
import { FormField } from '../../components/FormField';
import type { AdministrationUser, UserFormErrors, UserFormValues } from '../../types/administration';
import { userRoles, userStatuses } from './administrationUtils';

export function UserFormDialog({ title, initialValues, errors, isSelf, requirePassword, onSave, onClose }: { title: string; initialValues: UserFormValues; errors: UserFormErrors; isSelf?: boolean; requirePassword?: boolean; onSave: (values: UserFormValues) => void; onClose: () => void }) {
  const [values, setValues] = useState(initialValues);
  const first = useRef<HTMLInputElement>(null);
  useEffect(() => first.current?.focus(), []);
  return <div className="dialog-backdrop"><section className="confirm-dialog admin-dialog" role="dialog" aria-modal="true" aria-labelledby="user-dialog-title"><h2 id="user-dialog-title">{title}</h2>{isSelf && <p className="inline-message inline-warning">Tu propio rol y estado activo están protegidos.</p>}<div className="dialog-form"><FormField id="dialog-name" label="Nombre completo"><input ref={first} id="dialog-name" value={values.nombre} aria-invalid={Boolean(errors.nombre)} onChange={(e) => setValues({ ...values, nombre: e.target.value })} />{errors.nombre && <span className="field-error" role="alert">{errors.nombre}</span>}</FormField><FormField id="dialog-email" label="Correo"><input id="dialog-email" type="email" value={values.email} aria-invalid={Boolean(errors.email)} onChange={(e) => setValues({ ...values, email: e.target.value })} />{errors.email && <span className="field-error" role="alert">{errors.email}</span>}</FormField><FormField id="dialog-role" label="Rol"><select id="dialog-role" value={values.rol} disabled={isSelf} onChange={(e) => setValues({ ...values, rol: e.target.value as AdministrationUser['rol'] })}>{userRoles.map((role) => <option key={role}>{role}</option>)}</select></FormField><FormField id="dialog-status" label="Estado inicial"><select id="dialog-status" value={values.estado} disabled={isSelf} onChange={(e) => setValues({ ...values, estado: e.target.value as AdministrationUser['estado'] })}>{userStatuses.filter((s) => s !== 'Bloqueado').map((status) => <option key={status}>{status}</option>)}</select></FormField><FormField id="dialog-job" label="Cargo opcional"><input id="dialog-job" value={values.cargo ?? ''} maxLength={120} onChange={(e) => setValues({ ...values, cargo: e.target.value })} /></FormField>{requirePassword ? <><FormField id="dialog-password" label="Contraseña inicial"><input id="dialog-password" type="password" value={values.password ?? ''} aria-invalid={Boolean(errors.password)} onChange={(e) => setValues({ ...values, password: e.target.value })} /><small>Mínimo 8 caracteres; debe cumplir la política de seguridad configurada en la API.</small>{errors.password && <span className="field-error" role="alert">{errors.password}</span>}</FormField><FormField id="dialog-confirm" label="Confirmación de contraseña"><input id="dialog-confirm" type="password" value={values.confirmPassword ?? ''} aria-invalid={Boolean(errors.confirmPassword)} onChange={(e) => setValues({ ...values, confirmPassword: e.target.value })} />{errors.confirmPassword && <span className="field-error" role="alert">{errors.confirmPassword}</span>}</FormField></> : null}</div><div className="filter-actions"><Button variant="primary" onClick={() => onSave(values)}>Guardar</Button><Button onClick={onClose}>Cancelar</Button></div></section></div>;
}
