import { ApiError } from '../client/ApiError';
import type { ClassificationListRequestDto, ClassificationCatalogsDto, CreateClassificationRequestDto, UpdateClassificationRequestDto, CopyClassificationRequestDto, ClassificationWriteResponseDto, ClassificationSortByDto } from '../contracts/classifications';
import type { PaginatedResponse } from '../contracts/common';
import { classificationDomainToDto, classificationDtoToDomain } from '../mappers/classificationMapper';
import { mockClassifications } from '../../mocks/classifications';
import type { Classification } from '../../types/classification';
import type { ClassificationsService } from './ClassificationsService';

const pageSizes = [5, 10, 20];
const sortMap: Record<ClassificationSortByDto, keyof Classification> = { fiscalYear: 'ejercicio', instrument: 'instrumento', paymentDate: 'fechaPago', amount: 'monto', status: 'estado' };
function parseDate(value: string) { const [d, m, y] = value.split('-').map(Number); return new Date(y, m - 1, d).getTime(); }
function wait(signal?: AbortSignal) { return new Promise<void>((resolve, reject) => { if (signal?.aborted) { reject(new ApiError({ code: 'CANCELLED', message: 'Solicitud cancelada.' })); return; } const timer = window.setTimeout(resolve, 250); signal?.addEventListener('abort', () => { window.clearTimeout(timer); reject(new ApiError({ code: 'CANCELLED', message: 'Solicitud cancelada.' })); }, { once: true }); }); }
export class MockClassificationsService implements ClassificationsService {
  async list(request: ClassificationListRequestDto, signal?: AbortSignal): Promise<PaginatedResponse<Classification>> { await wait(signal); const pageSize = pageSizes.includes(request.pageSize) ? request.pageSize : 10; const search = request.search?.trim().toLowerCase() ?? ''; let rows = mockClassifications.map((r) => classificationDtoToDomain(classificationDomainToDto(r))).filter((r) => (!request.market || r.mercado === request.market) && (!request.source || r.origen === request.source) && (!request.fiscalYear || r.ejercicio === request.fiscalYear) && (!request.status || r.estado === request.status) && (!search || [r.instrumento, r.descripcion, r.secuenciaEvento].some((f) => f.toLowerCase().includes(search)))); const key = sortMap[request.sortBy]; rows = rows.sort((a, b) => { const mult = request.sortDirection === 'asc' ? 1 : -1; if (key === 'fechaPago') return (parseDate(a.fechaPago) - parseDate(b.fechaPago)) * mult; const left = a[key]; const right = b[key]; return (typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right), 'es-CL')) * mult; }); const totalItems = rows.length; const totalPages = totalItems === 0 ? 0 : Math.max(1, Math.ceil(totalItems / pageSize)); const page = Math.min(Math.max(1, request.page), Math.max(1, totalPages)); return { items: rows.slice((page - 1) * pageSize, page * pageSize), page, pageSize, totalItems, totalPages }; }
  async getCatalogs(signal?: AbortSignal): Promise<ClassificationCatalogsDto> { await wait(signal); return { markets: [...new Set(mockClassifications.map((r) => r.mercado))], sources: [...new Set(mockClassifications.map((r) => r.origen))], fiscalYears: [...new Set(mockClassifications.map((r) => r.ejercicio))], statuses: [...new Set(mockClassifications.map((r) => r.estado))] }; }
  async getById(id: string, signal?: AbortSignal) { await wait(signal); const row = mockClassifications.find((r) => r.id === id); if (!row) throw new ApiError({ code: 'NOT_FOUND', status: 404, message: 'No encontrado.' }); return { ...row }; }
  async create(request: CreateClassificationRequestDto, signal?: AbortSignal): Promise<ClassificationWriteResponseDto> { void request; void signal; throw new ApiError({ code: 'CONFIGURATION_ERROR', message: 'Escritura mock no integrada en este prompt.' }); }
  async update(id: string, request: UpdateClassificationRequestDto, rowVersion?: string, signal?: AbortSignal): Promise<ClassificationWriteResponseDto> { void id; void request; void rowVersion; void signal; throw new ApiError({ code: 'CONFIGURATION_ERROR', message: 'Escritura mock no integrada en este prompt.' }); }
  async copy(id: string, request: CopyClassificationRequestDto, signal?: AbortSignal): Promise<ClassificationWriteResponseDto> { void id; void request; void signal; throw new ApiError({ code: 'CONFIGURATION_ERROR', message: 'Copia mock no integrada en este prompt.' }); }
  async remove(id: string, rowVersion?: string, signal?: AbortSignal): Promise<void> { void id; void rowVersion; void signal; throw new ApiError({ code: 'CONFIGURATION_ERROR', message: 'Eliminación mock no integrada en este prompt.' }); }
}
