import type { AuditEvent, AuditFilters, AuditSortState } from '../../types/audit';
export const initialAuditFilters: AuditFilters = { texto:'', desde:'', hasta:'', usuario:'Todos', rol:'Todos', modulo:'Todos', accion:'Todos', resultado:'Todos', severidad:'Todos' };
export const auditModules = ['Autenticación','Calificaciones','Cargas','Reportes','Usuarios','Roles y Permisos','Auditoría','Respaldos'] as const;
export const auditActions = ['Inicio de sesión','Cierre de sesión','Consulta','Creación','Edición','Eliminación','Carga','Exportación','Cambio de estado','Cambio de permisos','Respaldo','Restauración'] as const;
export const auditResults = ['Exitoso','Advertencia','Fallido'] as const; export const auditSeverities = ['Informativa','Media','Alta'] as const;
export function formatDateTime(v:string){ return new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)); }
export function filterAudit(rows:AuditEvent[], f:AuditFilters){ const q=f.texto.trim().toLowerCase(); return rows.filter(r=>(!q||[r.id,r.usuarioNombre,r.entidad,r.entidadId,r.descripcion].some(v=>v.toLowerCase().includes(q)))&&(!f.desde||r.fechaHora.slice(0,10)>=f.desde)&&(!f.hasta||r.fechaHora.slice(0,10)<=f.hasta)&&(f.usuario==='Todos'||r.usuarioNombre===f.usuario)&&(f.rol==='Todos'||r.rol===f.rol)&&(f.modulo==='Todos'||r.modulo===f.modulo)&&(f.accion==='Todos'||r.accion===f.accion)&&(f.resultado==='Todos'||r.resultado===f.resultado)&&(f.severidad==='Todos'||r.severidad===f.severidad)); }
export function sortAudit(rows:AuditEvent[], sort:AuditSortState){ return [...rows].sort((a,b)=>{ const value=String(a[sort.key]).localeCompare(String(b[sort.key])); return sort.direction==='asc'?value:-value; }); }
export function auditSummary(rows:AuditEvent[]){ return { total:rows.length, exitosos:rows.filter(r=>r.resultado==='Exitoso').length, advertencias:rows.filter(r=>r.resultado==='Advertencia').length, fallidos:rows.filter(r=>r.resultado==='Fallido').length, alta:rows.filter(r=>r.severidad==='Alta').length, usuarios:new Set(rows.map(r=>r.usuarioId)).size }; }
export function validRange(desde:string,hasta:string){ return !desde || !hasta || desde <= hasta; }
