import { useMemo, useState } from 'react';
import { DemoNotice } from '../components/DemoNotice';
import { EmptyState, ErrorState, LoadingState } from '../components/ViewStates';
import { PageHeader } from '../components/PageHeader';
import { Pagination } from '../components/Pagination';
import { auditEvents } from '../mocks/auditEvents';
import type { AuditEvent, AuditSortKey, AuditSortState } from '../types/audit';
import { AuditDetailDialog } from '../features/audit/AuditDetailDialog';
import { AuditFilters } from '../features/audit/AuditFilters';
import { AuditSummary } from '../features/audit/AuditSummary';
import { AuditTable } from '../features/audit/AuditTable';
import { exportAudit } from '../features/audit/auditExport';
import { filterAudit, initialAuditFilters, sortAudit, validRange } from '../features/audit/auditUtils';
export function AuditPage(){ const [draft,setDraft]=useState(initialAuditFilters); const [active,setActive]=useState(initialAuditFilters); const [error,setError]=useState(''); const [demo,setDemo]=useState('normal'); const [sort,setSort]=useState<AuditSortState>({key:'fechaHora',direction:'desc'}); const [page,setPage]=useState({page:1,pageSize:10 as 10|20|50}); const [detail,setDetail]=useState<AuditEvent|null>(null); const filtered=useMemo(()=>sortAudit(filterAudit(auditEvents,active),sort),[active,sort]); const pageRows=filtered.slice((page.page-1)*page.pageSize,page.page*page.pageSize); const users=Array.from(new Set(auditEvents.map(e=>e.usuarioNombre))); const search=()=>{ if(!validRange(draft.desde,draft.hasta)){setError('La fecha desde no puede ser posterior a la fecha hasta.'); return;} setError(''); setActive(draft); setPage({...page,page:1});}; const clear=()=>{setDraft(initialAuditFilters); setActive(initialAuditFilters); setError(''); setPage({...page,page:1});}; const onSort=(key:AuditSortKey)=>setSort({key,direction:sort.key===key&&sort.direction==='asc'?'desc':'asc'}); return <section className="admin-page"><PageHeader title="Auditoría" description="Consulta simulada de trazabilidad y eventos relevantes del sistema."/><DemoNotice/><section className="demo-panel"><label htmlFor="audit-demo-state">Estado de demostración</label><select id="audit-demo-state" value={demo} onChange={e=>setDemo(e.target.value)}><option value="normal">Normal</option><option value="loading">Cargando</option><option value="error">Error</option></select><span>Control temporal separado de los filtros.</span></section><AuditSummary events={filtered}/><AuditFilters draft={draft} users={users} error={error} onChange={setDraft} onSearch={search} onClear={clear} onExport={()=>exportAudit(filtered)}/>{demo==='loading'&&<LoadingState message="Cargando auditoría simulada..."/>}{demo==='error'&&<ErrorState title="Error de demostración" description="Estado simulado para validar manejo de errores."/>}{demo==='normal'&&(filtered.length===0?<EmptyState title="Sin eventos" description="No hay eventos para los filtros aplicados." actionLabel="Limpiar filtros" onAction={clear}/>:<><AuditTable events={pageRows} sort={sort} onSort={onSort} onDetail={setDetail}/><Pagination pagination={page} totalItems={filtered.length} onPageChange={p=>setPage({...page,page:p})} onPageSizeChange={s=>setPage({page:1,pageSize:s as 10|20|50})}/></>)}{detail&&<AuditDetailDialog event={detail} onClose={()=>setDetail(null)}/>}</section>; }
