import type { BackupFilters, BackupRecord, BackupSortState } from '../../types/backup';
export const initialBackupFilters: BackupFilters={tipo:'Todos',alcance:'Todos',estado:'Todos',origen:'Todos',desde:'',hasta:'',texto:''};
export const backupTypes=['Completo','Diferencial','Configuración'] as const; export const backupScopes=['Base de datos','Configuración del sistema','Archivos de carga','Todos los módulos'] as const; export const backupStatuses=['Completado','En proceso','Fallido','Programado','Cancelado'] as const; export const backupTriggers=['Manual','Programado'] as const;
export function formatBytes(bytes:number){ if(bytes===0) return '0 B'; const units=['B','KB','MB','GB']; const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1); return `${(bytes/1024**i).toFixed(i===0?0:1)} ${units[i]}`; }
export function formatBackupDate(v:string){ return v?new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'Pendiente'; }
export function validBackupRange(desde:string,hasta:string){ return !desde||!hasta||desde<=hasta; }
export function filterBackups(rows:BackupRecord[],f:BackupFilters){ const q=f.texto.trim().toLowerCase(); return rows.filter(r=>(!q||[r.id,r.ejecutadoPor,r.descripcion,r.observaciones].some(v=>v.toLowerCase().includes(q)))&&(f.tipo==='Todos'||r.tipo===f.tipo)&&(f.alcance==='Todos'||r.alcance===f.alcance)&&(f.estado==='Todos'||r.estado===f.estado)&&(f.origen==='Todos'||r.origen===f.origen)&&(!f.desde||r.fechaInicio.slice(0,10)>=f.desde)&&(!f.hasta||r.fechaInicio.slice(0,10)<=f.hasta)); }
export function sortBackups(rows:BackupRecord[],sort:BackupSortState){ return [...rows].sort((a,b)=>{ const av=a[sort.key]; const bv=b[sort.key]; const v=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv)); return sort.direction==='asc'?v:-v;}); }
export function summarizeBackups(rows:BackupRecord[]){ return { total:rows.length, completados:rows.filter(r=>r.estado==='Completado').length, proceso:rows.filter(r=>r.estado==='En proceso').length, fallidos:rows.filter(r=>r.estado==='Fallido').length, programados:rows.filter(r=>r.estado==='Programado').length, espacio:rows.reduce((s,r)=>s+r.tamañoBytes,0)}; }
