import type { Classification, ClassificationSortKey } from '../../types/classification';
import type { UploadReviewItem } from '../../types/upload';
import type { ClassificationReportFilters, ReportSortState, UploadReportFilters } from '../../types/report';
import { money } from '../dashboard/dashboardUtils';
export function parseDate(value: string) { const [d,m,y]=value.includes('-')&&value.indexOf('-')===4 ? value.split('-').reverse() : value.split('-'); return new Date(Number(y), Number(m)-1, Number(d)); }
export function validRange(from: string, to: string) { return !from || !to || new Date(from) <= new Date(to); }
export const initialClassificationFilters: ClassificationReportFilters = { ejercicio:'Todos', mercado:'Todos', origen:'Todos', estado:'Todos', fechaDesde:'', fechaHasta:'', texto:'' };
export const initialUploadFilters: UploadReportFilters = { tipo:'Todos', estado:'Todos', responsable:'Todos', fechaDesde:'', fechaHasta:'' };
export function filterClassificationReport(rows: Classification[], f: ClassificationReportFilters) { const q=f.texto.trim().toLowerCase(); return rows.filter(r=>(f.ejercicio==='Todos'||String(r.ejercicio)===f.ejercicio)&&(f.mercado==='Todos'||r.mercado===f.mercado)&&(f.origen==='Todos'||r.origen===f.origen)&&(f.estado==='Todos'||r.estado===f.estado)&&(!f.fechaDesde||parseDate(r.fechaPago)>=new Date(f.fechaDesde))&&(!f.fechaHasta||parseDate(r.fechaPago)<=new Date(f.fechaHasta))&&(!q||[r.instrumento,r.descripcion,r.secuenciaEvento].some(v=>v.toLowerCase().includes(q)))); }
export function filterUploadReport(rows: UploadReviewItem[], f: UploadReportFilters) { return rows.filter(r=>(f.tipo==='Todos'||r.type===f.tipo)&&(f.estado==='Todos'||r.status===f.estado)&&(f.responsable==='Todos'||r.owner===f.responsable)&&(!f.fechaDesde||new Date(r.date)>=new Date(f.fechaDesde))&&(!f.fechaHasta||new Date(r.date)<=new Date(`${f.fechaHasta} 23:59`))); }
export function sortRows<T>(rows: T[], sort: ReportSortState) { return [...rows].sort((a,b)=>{ const av=(a as Record<string, unknown>)[sort.key]; const bv=(b as Record<string, unknown>)[sort.key]; const res = typeof av === 'number' && typeof bv === 'number' ? av-bv : String(av).localeCompare(String(bv)); return sort.direction==='asc'?res:-res; }); }
export function clsSummary(rows: Classification[]) { return { total: rows.length, monto: money.format(rows.reduce((s,r)=>s+r.monto,0)), Vigente: rows.filter(r=>r.estado==='Vigente').length, Pendiente: rows.filter(r=>r.estado==='Pendiente').length, Observada: rows.filter(r=>r.estado==='Observada').length, Rechazada: rows.filter(r=>r.estado==='Rechazada').length }; }
export function uploadSummary(rows: UploadReviewItem[]) { const totalRows=rows.reduce((s,r)=>s+r.totalRows,0), valid=rows.reduce((s,r)=>s+r.validRows,0), invalid=rows.reduce((s,r)=>s+r.invalidRows,0); return { total: rows.length, totalRows, valid, invalid, pct: totalRows ? `${Math.round((valid/totalRows)*100)}%` : '0%' }; }
export function nextSort(current: ReportSortState, key: ReportSortState['key']): ReportSortState { return { key, direction: current.key===key && current.direction==='asc' ? 'desc' : 'asc' }; }
export function pageInfo(total: number, page: number, size: number) { const start = total ? (page-1)*size+1 : 0; return { start, end: Math.min(page*size,total) }; }
export const sortableClassificationKeys: ClassificationSortKey[] = ['ejercicio','instrumento','fechaPago','monto','estado'];
